theme: jekyll-theme-minimal
title: Tom Savage - Chemical Engineering Postgraduate 
description: Currently at the University of Cambridge doing an MPhil by research in the department of Chemical Engineering & Biotechnology. Building knowledge graphs and creating agents to realise a digital-twin of the UK one triple at a time. Previously at Manchester, PhD at Imperial in machine learning and optimisation for bioprocesses. 
logo: /assets/img/IMG_2592.png
